export const data = {
  user: [
    {
      id: 1,
      username: "ahmad123",
      password: "1234567",
    },
    {
      id: 2,
      username: "ahmad1234",
      password: "12345678",
    },
    {
      id: 3,
      username: "ahmad1235",
      password: "12345679",
    },
    {
      id: 4,
      username: "ahmad1236",
      password: "12345671",
    },
  ],

  questions: [
    {
      id: "1",
      question: "يتم وضع الأهداف النهائية لمهمة التدقيق بعد ؟",
      choices: [
        "مراجعة تقييم المخاطر على مستوى المؤسسة .",
        "مراجعة وضع خطة التدقيق السنوية .",
        "إجراء تقييم المخاطر للناحية الخاضعة للتدقيق .",
        "التفاوض مع لجنة التدقيق حولها .",
      ],
      correctAnswer: "إجراء تقييم المخاطر للناحية الخاضعة للتدقيق .",
    },
    {
      id: "2",
      question:
        "يستطيع المدقق الداخلي تقييم وظيفة الإدارة في التخطيط من خلال تحديد ؟",
      choices: [
        "مسؤوليات المديرين والصلاحيات المفوضة لهم .",
        "فيما إذا كانت تعويضات الموظفين متناسبة مع الجدول الذي يصنف حدود التعويضات للموظف حسب درجته الوظيفية .",
        "فيما إذا كانت كل خطة من خطط الإدارة تتضمن وسائل لقياس مدى نجاح في تلك الخطة .",
        "فيما إذا كان قد تم وضع وتعميم معايير أداء جديدة عندما تصبح المعايير القديمة غير كافية أو غير فعالة .",
      ],
      correctAnswer:
        "فيما إذا كانت كل خطة من خطط الإدارة تتضمن وسائل لقياس مدى نجاح في تلك الخطة .",
    },
    {
      id: "3",
      question:
        "خلال أي مرحلة عملية التدقيق يقوم المدقق بتحديد الأهداف والضوابط الرقابية ذات العلاقة بالنشاط الخاضع للتدقيق ؟",
      choices: [
        "الاستقصاء التمهيدي .",
        "اختيار كادر التدقيق .",
        "إعداد برنامج التدقيق .",
        "إصدار تقرير التدقيق .",
      ],
      correctAnswer: "الاستقصاء التمهيدي .",
    },
    {
      id: "4",
      question:
        "أي من التالي يعتبر الشرح الأفضل للفرق بين أهداف التدقيق وإجراءات التدقيق ؟",
      choices: [
        "إجراءات التدقيق تحدد الأهداف العامة الواسعة ، أما أهداف التدقيق فتحدد العمل الواجب القيام به بشكل مفصل .",
        "يتم وضع أهداف التدقيق لكل مهمة على حدة ، إجراءات التدقيق تعتبر عامة من حيث التطبيق .",
        "أهداف التدقيق تحدد الإنجازات المحددة المطلوبة ، إجراءات التدقيق تحدد الطرق لتحقيق هذه الأهداف .",
        "إجراءات التدقيق وأهداف التدقيق متشابهة من حيث المبدأ .",
      ],
      correctAnswer:
        "أهداف التدقيق تحدد الإنجازات المحددة المطلوبة ، إجراءات التدقيق تحدد الطرق لتحقيق هذه الأهداف .",
    },
    {
      id: "5",
      question:
        "يضع المدقق الداخلي أهداف التدقيق عند التخطيط للتدقيق كي يحدد ما يجب إنجازه . أي مما يلي هو مسألة هامة يجب أخذها بعين الاعتبار عند وضع أهداف التدقيق ؟",
      choices: [
        "مؤهلات كادر التدقيق الذي سوف يقوم بالمهمة .",
        "أهداف الجهة الخاضعة للتدقيق وبنية الرقابة لديها .",
        "اقتراحات موظفي القسم الخاضع للتدقيق .",
        "الجهات التي ستتلقى تقرير التدقيق .",
      ],
      correctAnswer: "أهداف الجهة الخاضعة للتدقيق وبنية الرقابة لديها .",
    },
    {
      id: "6",
      question:
        "أظهرت مرحلة الاستقصاء التمهيدي للتدقيق على نشاط التوظيف أن مصاريف الفنادق والطيران تقريباً متساوية . تقوم سكرتيرة قسم التوظيف بحجوزات الفنادق والطيران . بناء على هذه المعلومات يجب أن يتضمن نطاق التدقيق ؟",
      choices: [
        "الأخذ بعين الاعتبار عوامل المنافسة المستخدمة في اختيار الفنادق .",
        "الاقتراح أن يقوم شخص آخر خارج قسم التوظيف بالقيام بحجوزات الفنادق والطيران .",
        "مقارنة تفاصلي مصاريف الفندق لكل متقدم في التقارير مع نسخ من الفواتير الصادرة عن الفندق مباشرة .",
        "الحصول على تأكيدات أن الحقوق القانونية للمتقدمين محمية عند إجراء المقابلات .",
      ],
      correctAnswer:
        "الأخذ بعين الاعتبار عوامل المنافسة المستخدمة في اختيار الفنادق .",
    },
    {
      id: "7",
      question:
        "تقوم بالتخطيط لمدة ثلاث سنوات لتدقيق جميع الفروع لوكالة تأجير سيارات عالمية كبيرة . الإدارة مهتمة بشكل خاص بالعمليات المعيارية للمحاسبة وتأجير السيارات ، ووظائف المخزون . أي من نماذج برامج التدقيق تعتبر الأكثر ملاءمة من أجل هذا المشروع ؟",
      choices: [
        "وضع برنامج تدقيق موحد واختباره من قبل قسم التدقيق الداخلي .",
        "وضع برامج تدقيق فردية من قبل المدقق الموكل بالمهمة بعد الاستقصاء التمهيدي لكل فرع .",
        "وضع قائمة لإجراءات التشغيل المعيارية للفرع .",
        "دليل الإرشاد المطور للصناعة .",
      ],
      correctAnswer:
        "وضع برنامج تدقيق موحد واختباره من قبل قسم التدقيق الداخلي .",
    },

    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
    {
      id: "",
      question: "",
      choices: ["", " ", "", ""],
      correctAnswer: "",
    },
  ],
};
